### ISSUE TITLE
Missing Instructions

### ISSUE THREAD

**Issue by yigitsever** [saidaltindis/anomaly-detection#54]
README.md does not include the steps to reproduce/run the included code. If reproducibility is not your intention for this repository feel free to close the issue.

**Comment by saidaltindis** [comment]
I'm planning to create another repository for the video feature extractor only while this repository includes pre-trained models, how to use pre-trained models and how to train new models about anomaly detection. Also, I want to generalize feature extracting process before doing so. Thus, I'm closing this issue right now. It will be re-open when splitting is done.
